travis:
  secure:
    BINSTAR_TOKEN: UdU8mvrzNOAdQUiMBrVGOuR7Dw5mKOQcOPDA2BBZl2zrkK9ekhJwlNzRHzGrZWGN+s4RbHIX3C5NCBRAogucwZjQLkpYyEWnbhO7Ax0U+6MFFuuyZCZUiT4snRLxz2N35l5/VYTQlDITPn4GbEcY6zngw8uTj+bEmyn9hYBOEVxKfMw1kWR+3l69Qj6veFOtzqtgrVynI+7wlGv5+ypN5Iz7Z2H+HbqCfkGpgndyxXkqf5vxzThWWUdqBu7ypTMecq+/n2KscT86ot0h3+CZIvrZdUWEhxVfHguSU+ZO//FCV0YtACcqLmboBjOr38+yUmBFVy1TVxJDYTDtFrF1/jBpTxa3OfxACJQwfTtzfRazf3IhJUOGcaNtF2Ac1PkeClwkLVlY2KQXIdgMYWyct8d36AmcDVSTN/+WYfrE+V0wgjAQAefNNWfMm0s3/V0q4fgqIMqvf+uofCQX9aDQdRZGtSY2pWN1bkj58i0jdioPni9m4bR13YnLsN73AdqqSMhHeBt5/iANgqzCCBY0vsp3ZeJM9dTQTSwz2PzgEWSzgui5wMfpvvMco8Av+9unfQztirf2JfxNyUYUW9+Se+ehid4AHdctamd+1JYZX5UB9m+3YVB5gKLqXyi4guhnqNaoc7IiwOEQxayd0AKQQMr+y4xheHXQThOA5D6yMiw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
